# goal
geometry_msgs/Pose goal_pose
float64[] initial_configuration
string planning_group
int32 number_of_waypoints
---
# result
moveit_msgs/RobotTrajectory planned_trajectory
bool success
---
# feedback
float64 percentage