slerp_test_client:
  goal_configuration: [0.607, -0.000, 0.690, 0.924, -0.383, 0.000, 0.000]
  initial_pose: [0, 0, 0, 0, 0, 0, 1]
  initial_configuration: []
  number_of_waypoints: 20
  planning_group: "panda_arm"
